### ISSUE TITLE
Download apk in another source than google

### ISSUE THREAD

**Issue by eetsceeck1** [pydio/cells-android-app#2] opened 2023-01-10 18:02 UTC
Hi, 

i just discovered your program through my self host server yunohost, 
it look awesome, but the problem is i cant download the program for my android cause i have degoogled phone without google play, i searched your app on fdroid but its not available, why don't you compile it and make it available on the "release" page? 

thank you.

**Comment by bsinou** [comment] 2023-01-19 07:25
This is a duplicate from issue #1 - Well done: I think you score a record - we're probably the only repo in the github world that has only 2 issues and the second is a duplicate of the first :)  (pun intented ... ) 

Anyway, for a more constructive answer about the publication in F-Droid, refer to issue #1 

The other solution would be to directly build the app from the source, everything is available and you can then install that directly on your phone.

Please rather start a thread in our [forum](https://forum.pydio.com) if you need some help doing so.

And BTW thanks a lot for your interest and feedback.

**Closed as not planned by bsinou** 2023-01-19 07:25 UTC

**Comment by eetsceeck1** [comment] 2023-01-19 14:33
at the day I did open this issue, after few minutes or hours (I don't remember), I saw my issue being deleted and gone, I didn't understand what's happening, I thought you just ignored my issue and are not interested to give any attention into it, so I deleted your program from my server including all the folders with the executables, 

I just saw your reply on my thunderbird and was really surprised you did reply to it, 

so first of all I want to thank you very much for your reply, 
and I really think its worth a try, it is definitely looks very interesting software at the whole manner, 

I do have some experience in compiling apk's with android studio, and its of course already installed on my machine cause in some cases I am compiling webview's apps, 
but to be honest, I am little bit stressed when I am thinking about compiling a program which i don't know, cause its always... always making problems, I don't know why, 
though to most developers do provide an explanations on how to compile, in many cases i am just getting sort of errors on the code, because of this missing and that missing, and need to install that and that and that, which took me to a loop of hours I many times, 

I do php, c#, and c++ programming for many years so I have experience in many kind of compiling, i found android projects to be the most difficult, the most problematic with errors no matter how your android studio is updated and include all of the required plugins, 

but i probably will give it a try, 

thank you again for your reply.

**Comment by bsinou** [comment] 2023-01-20 11:39
We worked hard so that builds are really easy to do with the project.
It should be no hassle to generate a local APK that you can then manually install on your device with Android Studio.
(we do that very regularly to test) 

Building a signed APK is more complicated and might not work without tweak out of the box on your system.

But, as I already said, do not hesitate to ask for help on the forum, someone (probably me :) ) will give you some help.
